### ISSUE TITLE
Modern UI

### ISSUE THREAD

**Issue by dipankardas011** [dipankardas011/PDF-Editor#17]

**Comment by hiteacheryouare** [comment]
HI!

I can totally help with this. I am quite proficient with tailwindcss.

However. tailwind only works with node.js. From looking around your file structure, it doesn't seem like you are. I can also help with this. Just keep in mind that I work the best in a tailwind, and I'm going to need it to design my UI

**Comment by dipankardas011** [comment]
Let me confirm with my friend🙂

**Comment by umgbhalla** [comment]
> HI!
> 
> I can totally help with this. I am quite proficient with tailwindcss.
> 
> However. tailwind only works with node.js. From looking around your file structure, it doesn't seem like you are. I can also help with this. Just keep in mind that I work the best in a tailwind, and I'm going to need it to design my UI

@hiteacheryouare 
https://tailwindcss.com/docs/installation/play-cdn
you can always use the cdn version to begin with, wouldn't require node or any packaging system

**Comment by hiteacheryouare** [comment]
Thank you. I totally forgot about the CDN version of it. I can use that if you wish

**Comment by dipankardas011** [comment]
@hiteacheryouare  Just conforming, are you going to work on the pull request for the design aspect?
If anything like port or get or post address to be exposed you may tell

**Comment by hiteacheryouare** [comment]
I only plan to work in the `./backEnd/web/` directory. I don't think that would expose any HTTP secrets if that's what you're worried about. And yes, I will use a pull request.

**Comment by dipankardas011** [comment]
👍🏼

**Comment by hiteacheryouare** [comment]
Here's what it looks like so far. Any suggestions?

![UI Screenshot](https://user-images.githubusercontent.com/82683251/163822351-14594a86-4b8b-499d-b1db-cab7363c9f7f.png)

**Comment by dipankardas011** [comment]
Looks good, just that unordered navigation be like horizontal and squishing 'pdf-editor' to left having majority portion.

**Comment by dipankardas011** [comment]
![Screenshot_20220418-212455_Twitter.jpg](https://user-images.githubusercontent.com/65275144/163835623-7921f1bd-53fc-4609-9694-96828319c05d.jpg)

**Comment by dipankardas011** [comment]
@hiteacheryouare 
You can take time as we both are having university exams till the end of May before which not much to do on this🙂
Hope you and your family are in a good state👍🏼

**Comment by dipankardas011** [comment]
I am adding a websiteDesign branch

**Comment by hiteacheryouare** [comment]
Thank you. Do you want me to post the PR going into that branch?

**Comment by dipankardas011** [comment]
you can still make pr so that in future you can continue

**Comment by dipankardas011** [comment]
> Thank you. Do you want me to post the PR going into that branch?

no by mistake written you can pr to the main branch

**Comment by dipankardas011** [comment]
@hiteacheryouare you can create PR
whatever you have done
so that it started👍🏼
