### ISSUE TITLE
Security Results

### ISSUE THREAD

**Issue by dipankardas011** [dipankardas011/PDF-Editor#79]
- Convert all the curl commands to fetch commands

**Comment by PrakritiRaw** [comment]
Hy @dipankardas011 , Can I take this up?

**Comment by dipankardas011** [comment]
@PrakritiRaw yes you can

**Comment by dipankardas011** [comment]
@PrakritiRaw yes you can

**Comment by dipankardas011** [comment]
don't forget to verify whether all the containers are able to communicate with each other
use the docker-compose one to verify if all are able to communicate ig for development its there

**Comment by PrakritiRaw** [comment]
kindly tell me the files which I need to check.

**Comment by dipankardas011** [comment]
https://github.com/dipankardas011/PDF-Editor/blob/main/src/frontend/server.js

**Comment by PrakritiRaw** [comment]
sorry sir I won't be able to continue with this issue.

**Comment by Manda-supraja26** [comment]
hi @dipankardas011  can i take this
